Create table and answer queries
keebot-png/Vet-Clinic pull request #1
Opened 2023-01-17 21:11 UTC by keebot-png

## The following criteria has been completed in line with project requirements:
- [x] Create a data base called 'vet_clinic'.
- [x] Created a table called 'animals'.
- [x] Inserted the correct data in the table.
- [x] Answered the questions below and captured screenshots of the results.

### Solutions to the questions
<details>
<summary>Find all animals whose name ends in "mon"</summary>
<img src="https://user-images.githubusercontent.com/101398701/213010074-48efe702-e62d-4e24-a6c9-4cfd9ae9aefe.PNG" width="500" />
</details>
<details>
<summary>List the name of all animals born between 2016 and 2019</summary>
<img src="https://user-images.githubusercontent.com/101398701/213010617-a47b89ea-c6df-49aa-b42f-404a6476ead8.png" width="500" />
</details>
<details>
<summary>List the name of all animals that are neutered and have less than 3 escape attempts</summary>
<img src="https://user-images.githubusercontent.com/101398701/213011007-04986f7e-1e76-4888-af55-33ea8ea62268.png" width="500" />
</details>
<details>
<summary>List the date of birth of all animals named either "Agumon" or "Pikachu"</summary>
<img src="https://user-images.githubusercontent.com/101398701/213011981-726d8645-a1b2-4a30-9ede-0bc085f2e146.png" width="500" />
</details>
<details>
<summary>List name and escape attempts of animals that weigh more than 10.5kg</summary>
<img src="https://user-images.githubusercontent.com/101398701/213012497-34688d05-e961-4df1-8615-3359dbd2fa74.png" width="500" />
</details>
<details>
<summary>Find all animals that are neutered</summary>
<img src="https://user-images.githubusercontent.com/101398701/213012717-04888c3f-f79c-4427-9212-75f1a98056cf.png" width="500" />
</details>
<details>
<summary>Find all animals not named Gabumon</summary>
<img src="https://user-images.githubusercontent.com/101398701/213012951-6a75381c-81d2-4cb4-8dc5-df8f4796f8f4.png" width="500" />
</details>
<details>
<summary>Find all animals with a weight between 10.4kg and 17.3kg</summary>
<img src="https://user-images.githubusercontent.com/101398701/213013214-12f9e661-6819-4177-a4f5-19a2b4302c77.png" width="500" />
</details>

2023-01-17 22:32 UTC, Ismailco requested changes
### Hi @keebot-png, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 22:32 UTC, Ismailco commented on schema.sql
> +    id INTEGER,
- [ ] [OPTIONAL] You can make the id column not null and autoincremented
e.g
```sql
  id int NOT NULL IDENTITY(1,1)
```

2023-01-17 22:32 UTC, Ismailco commented on schema.sql
> +    id INTEGER,
- [ ] [OPTIONAL] You could make the `id` column as primary key
```sql
PRIMARY KEY (id)
```

2023-01-17 22:32 UTC, Ismailco commented on queries.sql
> +SELECT * FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-12-31';
- [ ] This query should only list the `name of all animals` born between 2016 and 2019, kindly make sure to select only `name`s not all the data (`*`)

2023-01-17 22:32 UTC, Ismailco commented on queries.sql
> +SELECT * FROM animals WHERE neutered IS true AND escape_attempts < 3;
- [ ] Same here kindly make sure to list only the `names` of the animals not all the data (`*`)

2023-01-18 06:55 UTC, keebot-png commented
Thank you for this honest and thorough review @Ismailco. I have corrected my mistakes and updated the screen shots in the PR description.

2023-01-18 07:08 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

### Hey @keebot-png 👋

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Requirements
✔️ Following Linters

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 07:08 UTC, HAMMAS-SALEEM commented on README.md
**[Optional]**

- [ ] Kindly add **Key Features** and **Future Feature** section are still empty :basket: Kindly add fill these sections to make your readme descriptive :+1:

2023-01-18 08:23 UTC, merged